services:
  - type: web
    name: revision-server
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_APP_URL
        value: https://revisioncasitas.netlify.app 